import Head from 'next/head'
import { Aldrich } from '@next/font/google'

import Layout from './layout';
import Link from 'next/link';

const inter = Aldrich({
  weight: '400',
  style: 'normal',
})

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Legal AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className + ' h-screen flex items-center justify-center'}>
        <div className='flex flex-col items-center gap-y-4'>
          <h1 className='font-bold text-6xl'>
            Welcome to Legal AI
          </h1>
          <p className='text-2xl'>
            Where AI meets Law
          </p>

          {/* A button with lets get started and an arrow icon to navigate the user */}
          <Link
            href='/upload'
            className='flex items-center gap-x-2 bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded'>
            <span>Lets get started</span>
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
            </svg>
          </Link>
        </div>
      </main>
    </Layout>
  )
}
